name: track_my_stuff
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  google_fonts: ^8.1.0
  google_mlkit_object_detection: ^0.15.1
  image: ^4.5.2
  image_picker: any
  llama_cpp_dart: ^0.2.2
  objectbox: any
  objectbox_flutter_libs: any
  objective_c: any
  path_provider: any
  riverpod_annotation: ^4.0.2
  tflite_flutter: ^0.12.1
  uuid: any

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  mockito: ^5.6.4
  objectbox_generator: any
  riverpod_generator: any
  very_good_analysis: any

flutter:
  uses-material-design: true

  assets:
    - assets/models/minilm_l6_v2.tflite
    - assets/models/vision_model.gguf
    - assets/models/vision_mmproj.gguf
