// Mocks generated by Mockito 5.4.6 from annotations
// in track_my_stuff/test/features/items/data/ml/local_vision_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ffi' as _i4;
import 'dart:typed_data' as _i8;

import 'package:llama_cpp_dart/src/llama.dart' as _i3;
import 'package:llama_cpp_dart/src/llama_cpp.dart' as _i2;
import 'package:llama_cpp_dart/src/llama_input.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _Fakellama_cpp_0 extends _i1.SmartFake implements _i2.llama_cpp {
  _Fakellama_cpp_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Llama].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlama extends _i1.Mock implements _i3.Llama {
  MockLlama() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Pointer<_i2.llama_model> get model =>
      (super.noSuchMethod(
            Invocation.getter(#model),
            returnValue: _i5.dummyValue<_i4.Pointer<_i2.llama_model>>(
              this,
              Invocation.getter(#model),
            ),
          )
          as _i4.Pointer<_i2.llama_model>);

  @override
  _i4.Pointer<_i2.llama_vocab> get vocab =>
      (super.noSuchMethod(
            Invocation.getter(#vocab),
            returnValue: _i5.dummyValue<_i4.Pointer<_i2.llama_vocab>>(
              this,
              Invocation.getter(#vocab),
            ),
          )
          as _i4.Pointer<_i2.llama_vocab>);

  @override
  _i2.llama_batch get batch =>
      (super.noSuchMethod(
            Invocation.getter(#batch),
            returnValue: _i5.dummyValue<_i2.llama_batch>(
              this,
              Invocation.getter(#batch),
            ),
          )
          as _i2.llama_batch);

  @override
  _i3.LlamaStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i3.LlamaStatus.uninitialized,
          )
          as _i3.LlamaStatus);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  _i4.Pointer<_i2.llama_context> get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _i5.dummyValue<_i4.Pointer<_i2.llama_context>>(
              this,
              Invocation.getter(#context),
            ),
          )
          as _i4.Pointer<_i2.llama_context>);

  @override
  set model(_i4.Pointer<_i2.llama_model>? value) => super.noSuchMethod(
    Invocation.setter(#model, value),
    returnValueForMissingStub: null,
  );

  @override
  set vocab(_i4.Pointer<_i2.llama_vocab>? value) => super.noSuchMethod(
    Invocation.setter(#vocab, value),
    returnValueForMissingStub: null,
  );

  @override
  set batch(_i2.llama_batch? value) => super.noSuchMethod(
    Invocation.setter(#batch, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.llama_cpp getLib() =>
      (super.noSuchMethod(
            Invocation.method(#getLib, []),
            returnValue: _Fakellama_cpp_0(this, Invocation.method(#getLib, [])),
          )
          as _i2.llama_cpp);

  @override
  void createSlot(String? slotId) => super.noSuchMethod(
    Invocation.method(#createSlot, [slotId]),
    returnValueForMissingStub: null,
  );

  @override
  void setSlot(String? slotId) => super.noSuchMethod(
    Invocation.method(#setSlot, [slotId]),
    returnValueForMissingStub: null,
  );

  @override
  void freeSlot(String? slotId) => super.noSuchMethod(
    Invocation.method(#freeSlot, [slotId]),
    returnValueForMissingStub: null,
  );

  @override
  void setPrompt(String? prompt, {void Function(int, int)? onProgress}) =>
      super.noSuchMethod(
        Invocation.method(#setPrompt, [prompt], {#onProgress: onProgress}),
        returnValueForMissingStub: null,
      );

  @override
  (String, bool) getNext() =>
      (super.noSuchMethod(
            Invocation.method(#getNext, []),
            returnValue: (
              _i5.dummyValue<String>(this, Invocation.method(#getNext, [])),
              false,
            ),
          )
          as (String, bool));

  @override
  (String, bool, bool) getNextWithStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getNextWithStatus, []),
            returnValue: (
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getNextWithStatus, []),
              ),
              false,
              false,
            ),
          )
          as (String, bool, bool));

  @override
  _i6.Stream<String> generateText() =>
      (super.noSuchMethod(
            Invocation.method(#generateText, []),
            returnValue: _i6.Stream<String>.empty(),
          )
          as _i6.Stream<String>);

  @override
  _i6.Future<String> generateCompleteText({int? maxTokens}) =>
      (super.noSuchMethod(
            Invocation.method(#generateCompleteText, [], {
              #maxTokens: maxTokens,
            }),
            returnValue: _i6.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#generateCompleteText, [], {
                  #maxTokens: maxTokens,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  bool wasContextLimitReached() =>
      (super.noSuchMethod(
            Invocation.method(#wasContextLimitReached, []),
            returnValue: false,
          )
          as bool);

  @override
  int getRemainingContextSpace() =>
      (super.noSuchMethod(
            Invocation.method(#getRemainingContextSpace, []),
            returnValue: 0,
          )
          as int);

  @override
  _i6.Stream<String> generateWithMedia(
    String? prompt, {
    required List<_i7.LlamaInput>? inputs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateWithMedia, [prompt], {#inputs: inputs}),
            returnValue: _i6.Stream<String>.empty(),
          )
          as _i6.Stream<String>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  List<int> tokenize(String? text, bool? addBos) =>
      (super.noSuchMethod(
            Invocation.method(#tokenize, [text, addBos]),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  List<double> getEmbeddings(
    String? prompt, {
    bool? addBos = true,
    bool? normalize = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmbeddings,
              [prompt],
              {#addBos: addBos, #normalize: normalize},
            ),
            returnValue: <double>[],
          )
          as List<double>);

  @override
  void saveSession(String? path) => super.noSuchMethod(
    Invocation.method(#saveSession, [path]),
    returnValueForMissingStub: null,
  );

  @override
  bool loadSession(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#loadSession, [path]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Uint8List saveState() =>
      (super.noSuchMethod(
            Invocation.method(#saveState, []),
            returnValue: _i8.Uint8List(0),
          )
          as _i8.Uint8List);

  @override
  void loadState(_i8.Uint8List? stateData) => super.noSuchMethod(
    Invocation.method(#loadState, [stateData]),
    returnValueForMissingStub: null,
  );
}
