// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/items/data/objectbox/entities/obx_item.dart';
import 'features/items/data/objectbox/entities/obx_storage_container.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8209660961616150004),
    name: 'ObxItem',
    lastPropertyId: const obx_int.IdUid(8, 1752821948716486324),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3170320275972677133),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1602586354031305328),
        name: 'domainId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 9152523154553510848),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7198582446819660948),
        name: 'containerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2988847192137431940),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3457872147779255392),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5960586229453252678),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4848435399907978043),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 179244632390421209),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1752821948716486324),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3434395577247600285),
    name: 'ObxStorageContainer',
    lastPropertyId: const obx_int.IdUid(7, 1971262679901463376),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6389123881123913010),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 612872124333564145),
        name: 'domainId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 1073939660339284209),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3900117300042925726),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6043857411571692321),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1668808424618534586),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 178597187360689808),
        name: 'parentId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1971262679901463376),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 3434395577247600285),
    lastIndexId: const obx_int.IdUid(3, 1073939660339284209),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ObxItem: obx_int.EntityDefinition<ObxItem>(
      model: _entities[0],
      toOneRelations: (ObxItem object) => [],
      toManyRelations: (ObxItem object) => {},
      getId: (ObxItem object) => object.obxId,
      setId: (ObxItem object, int id) {
        object.obxId = id;
      },
      objectToFB: (ObxItem object, fb.Builder fbb) {
        final domainIdOffset = fbb.writeString(object.domainId);
        final containerIdOffset = fbb.writeString(object.containerId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final imageUrlOffset = fbb.writeString(object.imageUrl);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(9);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, domainIdOffset);
        fbb.addOffset(2, containerIdOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(5, imageUrlOffset);
        fbb.addOffset(6, embeddingOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final domainIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final containerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = ObxItem(
          obxId: obxIdParam,
          domainId: domainIdParam,
          containerId: containerIdParam,
          name: nameParam,
          description: descriptionParam,
          imageUrl: imageUrlParam,
          embedding: embeddingParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    ObxStorageContainer: obx_int.EntityDefinition<ObxStorageContainer>(
      model: _entities[1],
      toOneRelations: (ObxStorageContainer object) => [],
      toManyRelations: (ObxStorageContainer object) => {},
      getId: (ObxStorageContainer object) => object.obxId,
      setId: (ObxStorageContainer object, int id) {
        object.obxId = id;
      },
      objectToFB: (ObxStorageContainer object, fb.Builder fbb) {
        final domainIdOffset = fbb.writeString(object.domainId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final imageUrlOffset = fbb.writeString(object.imageUrl);
        final parentIdOffset = object.parentId == null
            ? null
            : fbb.writeString(object.parentId!);
        fbb.startTable(8);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, domainIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, imageUrlOffset);
        fbb.addOffset(5, parentIdOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final domainIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final parentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = ObxStorageContainer(
          obxId: obxIdParam,
          domainId: domainIdParam,
          name: nameParam,
          description: descriptionParam,
          imageUrl: imageUrlParam,
          parentId: parentIdParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ObxItem] entity fields to define ObjectBox queries.
class ObxItem_ {
  /// See [ObxItem.obxId].
  static final obxId = obx.QueryIntegerProperty<ObxItem>(
    _entities[0].properties[0],
  );

  /// See [ObxItem.domainId].
  static final domainId = obx.QueryStringProperty<ObxItem>(
    _entities[0].properties[1],
  );

  /// See [ObxItem.containerId].
  static final containerId = obx.QueryStringProperty<ObxItem>(
    _entities[0].properties[2],
  );

  /// See [ObxItem.name].
  static final name = obx.QueryStringProperty<ObxItem>(
    _entities[0].properties[3],
  );

  /// See [ObxItem.description].
  static final description = obx.QueryStringProperty<ObxItem>(
    _entities[0].properties[4],
  );

  /// See [ObxItem.imageUrl].
  static final imageUrl = obx.QueryStringProperty<ObxItem>(
    _entities[0].properties[5],
  );

  /// See [ObxItem.embedding].
  static final embedding = obx.QueryHnswProperty<ObxItem>(
    _entities[0].properties[6],
  );

  /// See [ObxItem.createdAt].
  static final createdAt = obx.QueryDateProperty<ObxItem>(
    _entities[0].properties[7],
  );
}

/// [ObxStorageContainer] entity fields to define ObjectBox queries.
class ObxStorageContainer_ {
  /// See [ObxStorageContainer.obxId].
  static final obxId = obx.QueryIntegerProperty<ObxStorageContainer>(
    _entities[1].properties[0],
  );

  /// See [ObxStorageContainer.domainId].
  static final domainId = obx.QueryStringProperty<ObxStorageContainer>(
    _entities[1].properties[1],
  );

  /// See [ObxStorageContainer.name].
  static final name = obx.QueryStringProperty<ObxStorageContainer>(
    _entities[1].properties[2],
  );

  /// See [ObxStorageContainer.description].
  static final description = obx.QueryStringProperty<ObxStorageContainer>(
    _entities[1].properties[3],
  );

  /// See [ObxStorageContainer.imageUrl].
  static final imageUrl = obx.QueryStringProperty<ObxStorageContainer>(
    _entities[1].properties[4],
  );

  /// See [ObxStorageContainer.parentId].
  static final parentId = obx.QueryStringProperty<ObxStorageContainer>(
    _entities[1].properties[5],
  );

  /// See [ObxStorageContainer.createdAt].
  static final createdAt = obx.QueryDateProperty<ObxStorageContainer>(
    _entities[1].properties[6],
  );
}
