// Mocks generated by Mockito 5.4.6 from annotations
// in track_my_stuff/test/features/items/presentation/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:track_my_stuff/core/interfaces/local_database_interface.dart'
    as _i2;
import 'package:track_my_stuff/features/items/domain/item.dart' as _i5;
import 'package:track_my_stuff/features/items/domain/storage_container.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ILocalDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalDatabase extends _i1.Mock implements _i2.ILocalDatabase {
  MockILocalDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveContainer(_i4.StorageContainer? container) =>
      (super.noSuchMethod(
            Invocation.method(#saveContainer, [container]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.StorageContainer>> getAllContainers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContainers, []),
            returnValue: _i3.Future<List<_i4.StorageContainer>>.value(
              <_i4.StorageContainer>[],
            ),
          )
          as _i3.Future<List<_i4.StorageContainer>>);

  @override
  _i3.Future<_i4.StorageContainer?> getContainer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getContainer, [id]),
            returnValue: _i3.Future<_i4.StorageContainer?>.value(),
          )
          as _i3.Future<_i4.StorageContainer?>);

  @override
  _i3.Future<void> deleteContainer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteContainer, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveItem(_i5.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#saveItem, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Item>> getItemsInContainer(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsInContainer, [containerId]),
            returnValue: _i3.Future<List<_i5.Item>>.value(<_i5.Item>[]),
          )
          as _i3.Future<List<_i5.Item>>);

  @override
  _i3.Future<_i5.Item?> getItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getItem, [id]),
            returnValue: _i3.Future<_i5.Item?>.value(),
          )
          as _i3.Future<_i5.Item?>);

  @override
  _i3.Future<void> deleteItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Item>> searchItemsByVector(
    List<double>? vectorEmbedding, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchItemsByVector,
              [vectorEmbedding],
              {#limit: limit},
            ),
            returnValue: _i3.Future<List<_i5.Item>>.value(<_i5.Item>[]),
          )
          as _i3.Future<List<_i5.Item>>);
}
